
import { Language, TargetType, SpaceTarget, View, GroundStation } from './types';
import { PhysicsEngine } from './utils';

// Mapping for Data Values
export const TYPE_LABELS = {
  [Language.EN]: {
    [TargetType.SATELLITE]: "Satellite",
    [TargetType.DEBRIS]: "Space Debris",
    [TargetType.ASTEROID]: "Asteroid (NEO)",
    [TargetType.STATION]: "Space Station",
  },
  [Language.CN]: {
    [TargetType.SATELLITE]: "人造卫星",
    [TargetType.DEBRIS]: "太空垃圾",
    [TargetType.ASTEROID]: "近地小行星",
    [TargetType.STATION]: "空间站",
  },
  [Language.JP]: {
    [TargetType.SATELLITE]: "人工衛星",
    [TargetType.DEBRIS]: "宇宙デブリ",
    [TargetType.ASTEROID]: "地球近傍小惑星",
    [TargetType.STATION]: "宇宙ステーション",
  },
};

export const RISK_LABELS = {
  [Language.EN]: { LOW: "Stable", MEDIUM: "Caution", HIGH: "High Risk", CRITICAL: "Critical" },
  [Language.CN]: { LOW: "稳定", MEDIUM: "注意", HIGH: "高风险", CRITICAL: "严重" },
  [Language.JP]: { LOW: "安定", MEDIUM: "注意", HIGH: "高リスク", CRITICAL: "危険" },
};

// Real Ground Stations
export const GROUND_STATIONS: GroundStation[] = [
  { id: 'DSN-1', name: 'Goldstone (USA)', lat: 35.426, lon: -116.89, alt: 1.0 },
  { id: 'DSN-2', name: 'Madrid (ESP)', lat: 40.425, lon: -4.248, alt: 0.8 },
  { id: 'DSN-3', name: 'Canberra (AUS)', lat: -35.401, lon: 148.98, alt: 0.6 },
];

export const TRANSLATIONS = {
  [Language.EN]: {
    appTitle: "ASTROSENTINEL",
    subtitle: "Deep Space Situational Awareness",
    nav: {
      dashboard: "Dashboard",
      system: "System Monitor",
      targets: "Target Mgmt",
      alerts: "Alerts",
      control: "Control Center",
    },
    dashboard: {
      targets: "Active Targets",
      analysis: "Mission Analysis",
      orbitToggle: "Orbit Lines",
      resume: "Real-time",
      simulation: "Simulation",
      scanning: "Scanning sector...",
      selectTarget: "Select target for detailed telemetry.",
      risk: "Risk Level",
      telemetry: "TELEMETRY DATA",
      signal: "SIGNAL LOCKED",
      source: "SOURCE",
      camControl: "CAMERA CONTROL",
      search: "Search Target ID/Name...",
      livePos: "REAL-TIME ORBITAL STATE",
      latitude: "LATITUDE",
      longitude: "LONGITUDE",
      altitude: "ALTITUDE",
      velocity: "VELOCITY",
      groundLink: "GROUND STATION LINK",
      passPred: "PASS PREDICTION",
      nextPass: "Next Acquisition",
      noLink: "NO ACTIVE LINK",
      acquiring: "ACQUIRING...",
      linked: "LINK ESTABLISHED",
    },
    system: {
      title: "System Status Dashboard",
      cpu: "CPU Load (24h)",
      mem: "Memory Usage",
      net: "Network Traffic",
      sensors: "Sensor Array Status",
      power: "Power Grid Distribution",
      topology: "Active Sessions",
      online: "ONLINE",
      offline: "OFFLINE",
      calibrating: "CALIBRATING",
      logs: "Access Logs",
      requests: "REQ/s",
      latency: "LATENCY",
    },
    targets: {
      title: "Orbital Object Database",
      manage: "Manage Groups",
      filter: "Filter Class",
      addNew: "Import TLE",
      edit: "Edit Target",
      delete: "Remove",
      tableID: "ID",
      tableName: "Designation",
      tableType: "Class",
      tableGroup: "Group",
      tableOrbit: "Orbit Param",
      action: "Action",
      all: "All Targets",
      modalTitle: "Import TLE Data",
      editTitle: "Edit Target Parameters",
      confirm: "Import Data",
      save: "Save Changes",
      cancel: "Cancel",
      tlePlaceholder: "Paste 2-Line Element Set here...",
    },
    alerts: {
      title: "Early Warning System",
      noAlerts: "No active critical alerts in current sector.",
      critical: "CRITICAL",
      warning: "WARNING",
      info: "INFO",
    },
    control: {
      title: "Command & Control",
      timeControl: "Temporal Simulation Engine",
      realtime: "Real-time Sync",
      simMode: "Simulation Mode",
      speed: "Time Dilation",
      defcon: "DEFCON Level",
      override: "Manual Override",
      shutdown: "Emergency Shutdown",
      commLink: "Secure Comm Link",
      active: "ACTIVE",
      standby: "STANDBY",
      logConsole: "Command Log",
    },
    genAiPrompt: "Calculating orbital mechanics...",
    footer: "USSPACECOM // CLASSIFIED // EYES ONLY",
  },
  [Language.CN]: {
    appTitle: "天哨系统",
    subtitle: "深空目标轨道态势感知",
    nav: {
      dashboard: "态势大屏",
      system: "系统监控",
      targets: "天体管理",
      alerts: "预警中心",
      control: "控制中心",
    },
    dashboard: {
      targets: "在轨目标",
      analysis: "任务分析",
      orbitToggle: "轨道显示",
      resume: "实时同步",
      simulation: "模拟模式",
      scanning: "正在扫描扇区...",
      selectTarget: "请选择目标以查看详细遥测数据。",
      risk: "风险等级",
      telemetry: "实时遥测数据",
      signal: "信号锁定",
      source: "数据源",
      camControl: "视角控制",
      search: "搜索目标编号/代号...",
      livePos: "实时轨道状态矢量",
      latitude: "纬度 (LAT)",
      longitude: "经度 (LON)",
      altitude: "高度 (ALT)",
      velocity: "速度 (VEL)",
      groundLink: "地面站链路状态",
      passPred: "过境预报",
      nextPass: "下次过境时间",
      noLink: "链路断开",
      acquiring: "正在捕获...",
      linked: "链路已建立",
    },
    system: {
      title: "系统综合监控仪表盘",
      cpu: "CPU 负载趋势 (24h)",
      mem: "内存占用历史",
      net: "网络吞吐量",
      sensors: "传感器阵列状态",
      power: "能源网格分配",
      topology: "活跃会话",
      online: "在线",
      offline: "离线",
      calibrating: "校准中",
      logs: "访问日志",
      requests: "请求/秒",
      latency: "延迟 (ms)",
    },
    targets: {
      title: "轨道目标数据库",
      manage: "分组管理",
      filter: "类别筛选",
      addNew: "导入 TLE",
      edit: "编辑目标",
      delete: "移除",
      tableID: "编号",
      tableName: "代号",
      tableType: "类别",
      tableGroup: "分组",
      tableOrbit: "轨道参数",
      action: "操作",
      all: "显示全部",
      modalTitle: "导入 TLE 轨道数据",
      editTitle: "编辑目标参数",
      confirm: "导入数据",
      save: "保存更改",
      cancel: "取消",
      tlePlaceholder: "在此处粘贴两行轨道要素 (TLE)...",
    },
    alerts: {
      title: "早期预警系统",
      noAlerts: "当前扇区无活跃的危急警报。",
      critical: "严重",
      warning: "警告",
      info: "信息",
    },
    control: {
      title: "指挥与控制中心",
      timeControl: "时间流模拟引擎",
      realtime: "实时同步",
      simMode: "模拟模式",
      speed: "时间流速 (倍率)",
      defcon: "防御等级 (DEFCON)",
      override: "手动接管",
      shutdown: "紧急关机",
      commLink: "安全通信链路",
      active: "活跃",
      standby: "待机",
      logConsole: "指令日志",
    },
    genAiPrompt: "正在计算轨道力学参数...",
    footer: "国家航天局 // 机密 // 仅限内部",
  },
  [Language.JP]: {
    appTitle: "アストロ・センチネル",
    subtitle: "深宇宙軌道状況認識システム",
    nav: {
      dashboard: "ダッシュボード",
      system: "システム監視",
      targets: "目標管理",
      alerts: "警報センター",
      control: "制御センター",
    },
    dashboard: {
      targets: "アクティブ目標",
      analysis: "ミッション分析",
      orbitToggle: "軌道表示",
      resume: "リアルタイム",
      simulation: "シミュレーション",
      scanning: "セクターをスキャン中...",
      selectTarget: "詳細テレメトリを表示するにはターゲットを選択してください。",
      risk: "リスクレベル",
      telemetry: "テレメトリデータ",
      signal: "信号ロック",
      source: "ソース",
      camControl: "カメラ制御",
      search: "ターゲットID/名称検索...",
      livePos: "リアルタイム軌道状態",
      latitude: "緯度",
      longitude: "経度",
      altitude: "高度",
      velocity: "速度",
      groundLink: "地上局リンク状態",
      passPred: "パス予測",
      nextPass: "次回捕捉",
      noLink: "リンクなし",
      acquiring: "捕捉中...",
      linked: "リンク確立",
    },
    system: {
      title: "システム総合ダッシュボード",
      cpu: "CPU負荷推移 (24h)",
      mem: "メモリ使用率",
      net: "ネットワークトラフィック",
      sensors: "センサーアレイ",
      power: "電力グリッド配分",
      topology: "アクティブセッション",
      online: "オンライン",
      offline: "オフライン",
      calibrating: "調整中",
      logs: "アクセスログ",
      requests: "REQ/s",
      latency: "遅延 (ms)",
    },
    targets: {
      title: "軌道物体データベース",
      manage: "グループ管理",
      filter: "クラスフィルタ",
      addNew: "TLEインポート",
      edit: "編集",
      delete: "削除",
      tableID: "ID",
      tableName: "名称",
      tableType: "クラス",
      tableGroup: "グループ",
      tableOrbit: "軌道パラメータ",
      action: "操作",
      all: "すべて表示",
      modalTitle: "TLEデータインポート",
      editTitle: "ターゲット編集",
      confirm: "インポート",
      save: "保存",
      cancel: "キャンセル",
      tlePlaceholder: "2行軌道要素(TLE)をここに貼り付け...",
    },
    alerts: {
      title: "早期警戒システム",
      noAlerts: "現在、重大なアラートはありません。",
      critical: "クリティカル",
      warning: "警告",
      info: "情報",
    },
    control: {
      title: "指揮統制センター",
      timeControl: "時間シミュレーション",
      realtime: "リアルタイム",
      simMode: "シミュレーション",
      speed: "時間の流れ (倍率)",
      defcon: "防衛レベル",
      override: "手動オーバーライド",
      shutdown: "緊急シャットダウン",
      commLink: "安全な通信リンク",
      active: "アクティブ",
      standby: "スタンバイ",
      logConsole: "コマンドログ",
    },
    genAiPrompt: "軌道力学を計算中...",
    footer: "宇宙作戦隊 // 極秘 // 内部のみ",
  },
};

// Helper to create targets with TLE
const createTLETarget = (id: string, name: string, type: TargetType, group: string, risk: any, tle1: string, tle2: string): SpaceTarget => {
  const orbit = PhysicsEngine.parseTLE(tle1, tle2);
  if (!orbit) throw new Error(`Invalid TLE for ${name}`);
  
  // Set custom colors based on type
  orbit.color = type === TargetType.STATION ? '#22d3ee' : 
                type === TargetType.DEBRIS ? '#ef4444' :
                type === TargetType.ASTEROID ? '#fbbf24' : '#34d399';

  return {
    id, name, type, group, riskLevel: risk, lastUpdate: '0.0s', 
    orbit, tle1, tle2
  };
};

// Real TLE Data
export const INITIAL_TARGETS: SpaceTarget[] = [
  createTLETarget(
    'ISS', 'ISS (ZARYA)', TargetType.STATION, 'LEO_STATIONS', 'LOW',
    '1 25544U 98067A   24068.52638889  .00016717  00000+0  30112-3 0  9993',
    '2 25544  51.6410 146.5012 0005329  32.5024  76.8921 15.49904501442976'
  ),
  createTLETarget(
    'CSS', 'TIANGONG', TargetType.STATION, 'LEO_STATIONS', 'LOW',
    '1 48274U 21035A   24068.55763889  .00032712  00000+0  34211-3 0  9998',
    '2 48274  41.4735 220.5521 0006221 240.1212 209.8872 15.59821421152142'
  ),
  createTLETarget(
    'HST', 'HUBBLE', TargetType.SATELLITE, 'OBSERVATORY', 'LOW',
    '1 20580U 90037B   24067.87500000  .00001471  00000+0  62822-4 0  9994',
    '2 20580  28.4693 100.1122 0002521  89.1122 270.9981 15.09001231211234'
  ),
  createTLETarget(
    'SL-1001', 'STARLINK-1001', TargetType.SATELLITE, 'CONSTELLATION', 'MEDIUM',
    '1 44713U 19074A   24068.12345678  .00000521  00000+0  52122-4 0  9999',
    '2 44713  53.0541  12.1122 0001221  78.1234 282.1234 15.06392131234567'
  ),
  createTLETarget(
    'FY-1C', 'FENGYUN 1C DEB', TargetType.DEBRIS, 'DEBRIS_FIELD', 'HIGH',
    '1 25730U 99025A   24068.11111111  .00000123  00000+0  12345-4 0  9991',
    '2 25730  98.6123 240.1234 0151234 120.1234 240.1234 14.12345678123456'
  ),
  // Manually constructed Asteroid (Mock TLE-like data structure)
  {
     id: '2024-BX1', name: '2024 BX1', type: TargetType.ASTEROID, group: 'NEO', riskLevel: 'CRITICAL', lastUpdate: '0s',
     orbit: {
        semiMajorAxis: 10000, 
        eccentricity: 0.4,
        inclination: 15,
        raan: 45,
        argPe: 30,
        meanAnomaly: 20,
        meanMotion: 2,
        color: '#fbbf24',
        epoch: Date.now()
     }
  }
];
