
import { Language, TargetType, SpaceTarget, View } from './types';

// Mapping for Data Values (e.g., "SATELLITE" -> "人造卫星")
export const TYPE_LABELS = {
  [Language.EN]: {
    [TargetType.SATELLITE]: "Satellite",
    [TargetType.DEBRIS]: "Space Debris",
    [TargetType.ASTEROID]: "Asteroid (NEO)",
    [TargetType.STATION]: "Space Station",
  },
  [Language.CN]: {
    [TargetType.SATELLITE]: "人造卫星",
    [TargetType.DEBRIS]: "太空垃圾",
    [TargetType.ASTEROID]: "近地小行星",
    [TargetType.STATION]: "空间站",
  },
  [Language.JP]: {
    [TargetType.SATELLITE]: "人工衛星",
    [TargetType.DEBRIS]: "宇宙デブリ",
    [TargetType.ASTEROID]: "地球近傍小惑星",
    [TargetType.STATION]: "宇宙ステーション",
  },
};

export const RISK_LABELS = {
  [Language.EN]: { LOW: "Stable", MEDIUM: "Caution", HIGH: "High Risk", CRITICAL: "Critical" },
  [Language.CN]: { LOW: "稳定", MEDIUM: "注意", HIGH: "高风险", CRITICAL: "严重" },
  [Language.JP]: { LOW: "安定", MEDIUM: "注意", HIGH: "高リスク", CRITICAL: "危険" },
};

export const TRANSLATIONS = {
  [Language.EN]: {
    appTitle: "ASTROSENTINEL",
    subtitle: "Deep Space Situational Awareness",
    nav: {
      dashboard: "Dashboard",
      system: "System Monitor",
      targets: "Target Mgmt",
      alerts: "Alerts",
      control: "Control Center",
    },
    dashboard: {
      targets: "Active Targets",
      analysis: "AI Intelligence Analysis",
      orbitToggle: "Orbit Lines",
      resume: "Real-time",
      simulation: "Simulation",
      scanning: "Scanning sector...",
      selectTarget: "Select target for detailed telemetry.",
      risk: "Risk Level",
      telemetry: "TELEMETRY DATA",
      signal: "SIGNAL LOCKED",
      source: "SOURCE",
      camControl: "CAMERA CONTROL",
    },
    system: {
      title: "System Status Monitor",
      cpu: "Core Processing",
      mem: "Memory Buffer",
      net: "Uplink Latency",
      sensors: "Sensor Array Status",
      power: "Power Grid Distribution",
      topology: "Network Topology",
      online: "ONLINE",
      offline: "OFFLINE",
      calibrating: "CALIBRATING",
      logs: "System Logs",
    },
    targets: {
      title: "Orbital Object Database",
      manage: "Manage Groups",
      filter: "Filter Class",
      addNew: "Add New Target",
      delete: "Remove",
      tableID: "ID",
      tableName: "Designation",
      tableType: "Class",
      tableGroup: "Group",
      tableOrbit: "Orbit Param",
      action: "Action",
      all: "All Targets",
      modalTitle: "Initialize Tracking",
      confirm: "Confirm",
      cancel: "Cancel",
    },
    alerts: {
      title: "Early Warning System",
      noAlerts: "No active critical alerts in current sector.",
      critical: "CRITICAL",
      warning: "WARNING",
      info: "INFO",
    },
    control: {
      title: "Command & Control",
      timeControl: "Temporal Simulation Engine",
      realtime: "Real-time Sync",
      simMode: "Simulation Mode",
      speed: "Time Dilation",
      defcon: "DEFCON Level",
      override: "Manual Override",
      shutdown: "Emergency Shutdown",
      commLink: "Secure Comm Link",
      active: "ACTIVE",
      standby: "STANDBY",
      logConsole: "Command Log",
    },
    genAiPrompt: "Initializing AI Analysis...",
    footer: "USSPACECOM // CLASSIFIED // EYES ONLY",
  },
  [Language.CN]: {
    appTitle: "天哨系统",
    subtitle: "深空目标轨道态势感知",
    nav: {
      dashboard: "态势大屏",
      system: "系统监控",
      targets: "天体管理",
      alerts: "预警中心",
      control: "控制中心",
    },
    dashboard: {
      targets: "在轨目标",
      analysis: "AI 智能情报分析",
      orbitToggle: "轨道显示",
      resume: "实时同步",
      simulation: "模拟模式",
      scanning: "正在扫描扇区...",
      selectTarget: "请选择目标以查看详细遥测数据。",
      risk: "风险等级",
      telemetry: "实时遥测数据",
      signal: "信号锁定",
      source: "数据源",
      camControl: "视角控制",
    },
    system: {
      title: "系统状态监控",
      cpu: "核心处理负载",
      mem: "内存缓冲池",
      net: "上行链路延迟",
      sensors: "传感器阵列状态",
      power: "能源网格分配",
      topology: "网络拓扑结构",
      online: "在线",
      offline: "离线",
      calibrating: "校准中",
      logs: "系统日志",
    },
    targets: {
      title: "轨道目标数据库",
      manage: "分组管理",
      filter: "类别筛选",
      addNew: "新增目标",
      delete: "移除",
      tableID: "编号",
      tableName: "代号",
      tableType: "类别",
      tableGroup: "分组",
      tableOrbit: "轨道参数",
      action: "操作",
      all: "显示全部",
      modalTitle: "初始化追踪任务",
      confirm: "确认添加",
      cancel: "取消",
    },
    alerts: {
      title: "早期预警系统",
      noAlerts: "当前扇区无活跃的危急警报。",
      critical: "严重",
      warning: "警告",
      info: "信息",
    },
    control: {
      title: "指挥与控制中心",
      timeControl: "时间流模拟引擎",
      realtime: "实时同步",
      simMode: "模拟模式",
      speed: "时间流速 (倍率)",
      defcon: "防御等级 (DEFCON)",
      override: "手动接管",
      shutdown: "紧急关机",
      commLink: "安全通信链路",
      active: "活跃",
      standby: "待机",
      logConsole: "指令日志",
    },
    genAiPrompt: "正在初始化 AI 分析...",
    footer: "国家航天局 // 机密 // 仅限内部",
  },
  [Language.JP]: {
    appTitle: "アストロ・センチネル",
    subtitle: "深宇宙軌道状況認識システム",
    nav: {
      dashboard: "ダッシュボード",
      system: "システム監視",
      targets: "目標管理",
      alerts: "警報センター",
      control: "制御センター",
    },
    dashboard: {
      targets: "アクティブ目標",
      analysis: "AI インテリジェンス",
      orbitToggle: "軌道表示",
      resume: "リアルタイム",
      simulation: "シミュレーション",
      scanning: "セクターをスキャン中...",
      selectTarget: "詳細テレメトリを表示するにはターゲットを選択してください。",
      risk: "リスクレベル",
      telemetry: "テレメトリデータ",
      signal: "信号ロック",
      source: "ソース",
      camControl: "カメラ制御",
    },
    system: {
      title: "システムステータス",
      cpu: "コア処理負荷",
      mem: "メモリバッファ",
      net: "アップリンク遅延",
      sensors: "センサーアレイ",
      power: "電力グリッド配分",
      topology: "ネットワークトポロジ",
      online: "オンライン",
      offline: "オフライン",
      calibrating: "調整中",
      logs: "システムログ",
    },
    targets: {
      title: "軌道物体データベース",
      manage: "グループ管理",
      filter: "クラスフィルタ",
      addNew: "新規ターゲット",
      delete: "削除",
      tableID: "ID",
      tableName: "名称",
      tableType: "クラス",
      tableGroup: "グループ",
      tableOrbit: "軌道パラメータ",
      action: "操作",
      all: "すべて表示",
      modalTitle: "追跡初期化",
      confirm: "確認",
      cancel: "キャンセル",
    },
    alerts: {
      title: "早期警戒システム",
      noAlerts: "現在、重大なアラートはありません。",
      critical: "クリティカル",
      warning: "警告",
      info: "情報",
    },
    control: {
      title: "指揮統制センター",
      timeControl: "時間シミュレーション",
      realtime: "リアルタイム",
      simMode: "シミュレーション",
      speed: "時間の流れ (倍率)",
      defcon: "防衛レベル",
      override: "手動オーバーライド",
      shutdown: "緊急シャットダウン",
      commLink: "安全な通信リンク",
      active: "アクティブ",
      standby: "スタンバイ",
      logConsole: "コマンドログ",
    },
    genAiPrompt: "AI分析を初期化中...",
    footer: "宇宙作戦隊 // 極秘 // 内部のみ",
  },
};

export const INITIAL_TARGETS: SpaceTarget[] = [
  {
    id: 'ISS-25544',
    name: 'ISS (Zarya)',
    type: TargetType.STATION,
    riskLevel: 'LOW',
    lastUpdate: '0.2s',
    group: 'LEO_STATIONS',
    orbit: { semiMajorAxis: 80, eccentricity: 0.0006, inclination: 51.64, raan: 120, argPe: 0, meanAnomaly: 0, period: 0.008, color: '#22d3ee' },
  },
  {
    id: 'CSS-48274',
    name: 'Tiangong (CSS)',
    type: TargetType.STATION,
    riskLevel: 'LOW',
    lastUpdate: '0.5s',
    group: 'LEO_STATIONS',
    orbit: { semiMajorAxis: 82, eccentricity: 0.0008, inclination: 41.47, raan: 240, argPe: 50, meanAnomaly: 180, period: 0.0082, color: '#f472b6' },
  },
  {
    id: 'HST-20580',
    name: 'Hubble Telescope',
    type: TargetType.SATELLITE,
    riskLevel: 'LOW',
    lastUpdate: '1.2s',
    group: 'OBSERVATORY',
    orbit: { semiMajorAxis: 90, eccentricity: 0.0003, inclination: 28.47, raan: 60, argPe: 120, meanAnomaly: 45, period: 0.009, color: '#a78bfa' },
  },
  {
    id: 'GPS-BIIR-11',
    name: 'GPS BIIR-11',
    type: TargetType.SATELLITE,
    riskLevel: 'LOW',
    lastUpdate: '2.1s',
    group: 'MEO_NAV',
    orbit: { semiMajorAxis: 250, eccentricity: 0.01, inclination: 55.0, raan: 0, argPe: 0, meanAnomaly: 90, period: 0.02, color: '#60a5fa' },
  },
  {
    id: 'SL-1120',
    name: 'Starlink-1120',
    type: TargetType.SATELLITE,
    riskLevel: 'MEDIUM',
    lastUpdate: '0.1s',
    group: 'CONSTELLATION',
    orbit: { semiMajorAxis: 75, eccentricity: 0.0001, inclination: 53.0, raan: 15, argPe: 90, meanAnomaly: 30, period: 0.0075, color: '#34d399' },
  },
  {
    id: 'DEB-FY1C',
    name: 'FENGYUN 1C DEB',
    type: TargetType.DEBRIS,
    riskLevel: 'HIGH',
    lastUpdate: '5.0s',
    group: 'DEBRIS_FIELD',
    orbit: { semiMajorAxis: 120, eccentricity: 0.15, inclination: 98.6, raan: 300, argPe: 45, meanAnomaly: 120, period: 0.012, color: '#ef4444' },
  },
  {
    id: 'AST-2024-BX1',
    name: '2024 BX1',
    type: TargetType.ASTEROID,
    riskLevel: 'CRITICAL',
    lastUpdate: '10s',
    group: 'NEO',
    orbit: { semiMajorAxis: 400, eccentricity: 0.45, inclination: 15.0, raan: 45, argPe: 30, meanAnomaly: 350, period: 0.05, color: '#fbbf24' },
  },
  {
    id: 'GALILEO-22',
    name: 'GSAT0222',
    type: TargetType.SATELLITE,
    riskLevel: 'LOW',
    lastUpdate: '3s',
    group: 'MEO_NAV',
    orbit: { semiMajorAxis: 280, eccentricity: 0.002, inclination: 56.0, raan: 120, argPe: 10, meanAnomaly: 150, period: 0.025, color: '#c084fc' },
  }
];
